# Generated by Django 3.0.7 on 2020-07-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='note',
            field=models.CharField(max_length=100),
        ),
    ]
