# Generated by Django 3.0.7 on 2020-07-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200702_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
