# Generated by Django 3.0.7 on 2020-07-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoText', models.CharField(max_length=100)),
                ('isCompleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
